ARG PHP_VERSION=8.4
FROM serversideup/php:${PHP_VERSION}-cli AS phpcli

##########
# S6 Build
##########
FROM phpcli AS s6-build

ARG CONF_PATH

USER root

ARG S6_DIR='/opt/s6/'
ARG S6_SRC_URL="https://github.com/just-containers/s6-overlay/releases/download"

# copy our scripts
COPY --chmod=755 $CONF_PATH /

RUN s6-install.sh

############
# BASE IMAGE
############
FROM phpcli AS base

ARG CONF_PATH

USER root

LABEL authors="Kirschbaum"
LABEL maintainer="Kirschbaum"

ENV AUTORUN_ENABLED=false
ENV AUTORUN_LARAVEL_MIGRATION=false

# copy our scripts
COPY --chmod=755 $CONF_PATH /

# copy s6-overlay from s6-build
COPY --from=s6-build /opt/s6/ /

RUN apt-get update \
&& apt-get upgrade -y

RUN install-php-extensions gd intl

###################
# Development image
###################
FROM base AS development

# Save the build arguments as a variable
ARG USER_ID
ARG GROUP_ID

# Drop back to our unprivileged user
USER www-data

##############
# Deploy image
##############
FROM base AS deploy

ARG CUSTOM_CONF_PATH
ARG DEPLOY_PATH=/.sst/laravel/deploy
ARG PHP_OPCACHE_ENABLE=1

ENV CONTAINER_TYPE=cli

# OPcache, on unless `config.opcache` is false
ENV PHP_OPCACHE_ENABLE=${PHP_OPCACHE_ENABLE}

COPY --chown=www-data:www-data . /var/www/html
COPY --chown=www-data:www-data $DEPLOY_PATH/.env /var/www/html/.env

# Fix S6 Overlay issues with Big Cloud PaaS (https://github.com/serversideup/docker-php/pull/376#issuecomment-2179262427)
RUN chown -R www-data:www-data /run

# Copy the deployment script the component writes into .sst/laravel
COPY --chmod=755 $DEPLOY_PATH/60-deploy.sh /etc/entrypoint.d/60-deploy.sh

# Copy this worker's generated s6-overlay services. It comes last so every
# layer above is the same for all workers and comes from the build cache.
RUN test -n "$CUSTOM_CONF_PATH"
COPY --chmod=755 $CUSTOM_CONF_PATH /

USER www-data

ENTRYPOINT ["entrypoint.sh"]

# Set stop signal to SIGQUIT for a graceful shutdown instead of S6's preferred SIGTERM (https://github.com/just-containers/s6-overlay/issues/586)
STOPSIGNAL SIGQUIT

CMD ["/init"]
